import Section2 from '../../components/Section2'
import Section3 from '../../components/Section3'
import Section4 from '../../components/Section4'
import Section5 from '../../components/Section5'
import Section6 from '../../components/Section6'
import Section7 from '../../components/Section7'
import Head from 'next/head'
import Image from 'next/image'
import Header from './../../components/Header'
import Footer from './../../components/Footer'
import Main from './../../components/Main'



export default function Home() {
  return (
    <>
      <Head>
        <title>Tailwind Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
      <Header/>
<Main/>
      </section>
      <Section2/>
      <Section3/>
      <Section4/>
      <Section5/>
      <Section6/>
      <Section7/>
      <Footer/>
    </>
  )
}
