import Section2 from '../../components/Section2'
import Section3 from '../../components/Section3'
import Head from 'next/head'
import Image from 'next/image'
import Header from './../../components/Header'
import Main from './../../components/Main'


export default function Home() {
  return (
    <>
      <Head>
        <title>Tailwind Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
      <Header/>
<Main/>
      </section>
      <Section2/>
      <Section3/>
    </>
  )
}
